# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-29 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='order',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
