# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-17 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_add_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
